apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin
type: Opaque
data:
  url: "{{POSTGRES_URL}}"
  hostname: "{{POSTGRES_HOSTNAME}}"
  database: "{{POSTGRES_DATABASE}}"
  username: "{{POSTGRES_USERNAME}}"
  password: "{{POSTGRES_PASSWORD}}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hmb-svr
spec:
  selector:
    matchLabels:
      app: hmb-svr
  template:
    metadata:
      labels:
        app: hmb-svr
    spec:
      containers:
        - name: hmb-svr
          image: "{{IMAGE}}"
          env:
            - name: DATABASE_OPTION
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: url
            - name: SERVER_PORT
              value: "80"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hmb-svr
spec:
  selector:
    app: hmb-svr
  ports:
    - port: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: hmb-ssl
spec:
  domains:
    - "graph.hmbgaq.org"
    - "api.hmbgaq.org"
    - "www.hmbgaq.org"
    - "bible.hmbgaq.org"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hmb-svr-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.global-static-ip-name: "hmb-ip"
    networking.gke.io/managed-certificates: hmb-ssl
spec:
  rules:
    - host: "graph.hmbgaq.org"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hmb-svr
                port:
                  number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
type: Opaque
data:
  username: "{{KEYCLOAK_ADMIN_USERNAME}}"
  password: "{{KEYCLOAK_ADMIN_PASSWORD}}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: bitnami/keycloak:21.1.1
          env:
            - name: KEYCLOAK_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin
                  key: username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin
                  key: password
            - name: KEYCLOAK_DATABASE_VENDOR
              value: "postgresql"
            - name: KEYCLOAK_DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: hostname
            - name: KEYCLOAK_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: database
            - name: KEYCLOAK_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: username
            - name: KEYCLOAK_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: password
            - name: KEYCLOAK_DATABASE_SCHEMA
              value: "keycloak"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 80
