# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "graph",
    "application",
    "auth"
]


[patch.crates-io]
keycloak = { git = "https://github.com/egoavara/keycloak.git" }