name: Deploy

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        required: true
        default: next-patch
        description: "Versioning type"
        options:
          - "latest"
          - "manual"
      version:
        type: string
        required: false
        description: "Version to set"
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  gke_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0.4.0"
        with:
          workload_identity_provider: ${{ secrets.GKE_WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{ secrets.GKE_SERVICE_ACCOUNT }}
      - name: GKE setup
        uses: google-github-actions/get-gke-credentials@v0.4.0
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_LOCATION }}
      - name: Kubernetest Apply
        run: |
          if [[ "${{ inputs.type }}" == "latest" ]]; then
            sed -i 's/{{IMAGE}}/ghcr.io\/abyssal-debuggers\/hmb-svr:latest/' ./.k8s/deploy.yml
          elif [[ "${{ inputs.type }}" == "manual" ]]; then
            sed -i 's/{{IMAGE}}/ghcr.io\/abyssal-debuggers\/hmb-svr:${{ inputs.version }}/' ./.k8s/deploy.yml
          fi
          
          POSTGRES_URL=$(echo 'postgres://${{ secrets.POSTGRES_USERNAME }}:${{ secrets.POSTGRES_PASSWORD }}@${{ env.POSTGRES_HOSTNAME }}/${{ env.POSTGRES_DATABASE }}' | base64)
          POSTGRES_HOSTNAME=$(echo '${{ env.POSTGRES_HOSTNAME }}' | base64)
          POSTGRES_DATABASE=$(echo '${{ env.POSTGRES_DATABASE }}' | base64 )
          POSTGRES_USERNAME=$(echo '${{ secrets.POSTGRES_USERNAME }}' | base64)
          POSTGRES_PASSWORD=$(echo '${{ secrets.POSTGRES_PASSWORD }}' | base64)
          
          KEYCLOAK_ADMIN_USERNAME=$(echo '${{ secrets.KEYCLOAK_ADMIN_USERNAME }}' | base64)
          KEYCLOAK_ADMIN_PASSWORD=$(echo '${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}' | base64)
          
          sed -i "s/{{POSTGRES_URL}}/$POSTGRES_URL/" ./.k8s/deploy.yml
          sed -i "s/{{POSTGRES_HOSTNAME}}/$POSTGRES_HOSTNAME/" ./.k8s/deploy.yml
          sed -i "s/{{POSTGRES_DATABASE}}/$POSTGRES_DATABASE/" ./.k8s/deploy.yml
          sed -i "s/{{POSTGRES_USERNAME}}/$POSTGRES_USERNAME/" ./.k8s/deploy.yml
          sed -i "s/{{POSTGRES_PASSWORD}}/$POSTGRES_PASSWORD/" ./.k8s/deploy.yml
          
          sed -i "s/{{KEYCLOAK_ADMIN_USERNAME}}/$KEYCLOAK_ADMIN_USERNAME/" ./.k8s/deploy.yml
          sed -i "s/{{KEYCLOAK_ADMIN_PASSWORD}}/$KEYCLOAK_ADMIN_PASSWORD/" ./.k8s/deploy.yml
          
          cat ./.k8s/deploy.yml
          
          kubectl apply -f ./.k8s/deploy.yml
